# Generated by Django 5.1.7 on 2025-03-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_no", models.IntegerField()),
                ("roll_numbers", models.CharField(max_length=255)),
                ("student_name", models.CharField(max_length=255)),
                ("mentor", models.CharField(max_length=255)),
                ("primary_sdg_mapped", models.CharField(max_length=255)),
                ("project_title", models.CharField(max_length=255)),
                ("project_description", models.TextField()),
            ],
        ),
    ]
