# Generated by Django 5.1.7 on 2025-03-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fsd_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentproject",
            old_name="primary_sdg_mapped",
            new_name="primary_sdg",
        ),
    ]
